# action.yml
name: 'Dolt Action'
description: 'Helper tool for executing Dolt commands'
inputs:
  remote:
    description: 'Dolt remote object store path'
    required: true
    default: ''
  run:
    description: '(optional) Fine-tune data with a custom SQL query'
    required: true
    default: ''
  branch:
    description: 'Dolt branch name (will create if does not exist)'
    required: false
    default: 'master'
  push:
    description: '`False` if dry-run. Defaults to `True`'
    required: false
    default: true
  dolthub_credential:
    description: 'Cred used to authenticate dolthub'
    required: false
    default: ''
  google_credential:
    description: 'Cred used to push to a gcloud bucket'
    required: false
    default: ''
  commit_message:
    description: 'Dolt commit message'
    required: false
    default: 'Automated GitHub-Actions commit'
  commit_user_name:
    description: 'Name used for the commit user'
    required: false
    default: 'GitHub Actions'
  commit_user_email:
    description: 'Email address used for the commit user'
    required: false
    default: 'actions@github.com'
  commit_author:
    description: 'Value used for the commit author. Defaults to the username of whoever triggered this workflow run.'
    required: false
    default: '${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>'
  tag_name:
    description: ''
    required: false
    default: ''
  tag_message:
    description: ''
    required: false
    default: ''
  tag_ref:
    description: ''
    required: false
    default: ''
outputs:
  commit:
    description: "Commit hash executed during the workflow run"
runs:
  using: 'docker'
  image: 'Dockerfile'
