# action.yml
name: 'Dolt Action'
description: 'Helper tool for executing Dolt commands'
inputs:
  remote:
    description: 'Dolt remote object store path'
    required: true
    default: ''
  before:
    description: '(optional) Run command after before commit'
    required: true
    default: ''
  branch:
    description: '(optional) Dolt branch name (will create if does not exist)'
    required: false
    default: 'master'
  push:
    description: '(optional) `False` if dry-run. Defaults to `True`'
    required: false
    default: true
  dolthub_credential:
    description: '(optional) Cred used to authenticate dolthub'
    required: false
    default: ''
  google_credential:
    description: '(optional) Cred used to authenticate gcloud'
    required: false
    default: ''
  commit_message:
    description: '(optional) Dolt commit message'
    required: false
    default: 'Automated GitHub-Actions commit'
  commit_user_name:
    description: '(optional) Name used for the commit user'
    required: false
    default: 'GitHub Actions'
  commit_user_email:
    description: '(optional) Email address used for the commit user'
    required: false
    default: 'actions@github.com'
  commit_author:
    description: '(optional) Value used for the commit author. Defaults to the username of whoever triggered this workflow run.'
    required: false
    default: '${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>'
  tag_name:
    description: '(optional) Dolt tag name'
    required: false
    default: ''
  tag_message:
    description: '(optional) Dolt tag message'
    required: false
    default: ''
  tag_ref:
    description: '(optional) Tag branch or commit, default `HEAD`'
    required: false
    default: 'HEAD'
  after:
    description: '(optional) Run command after commit'
    required: false
    default: ''
  clear:
    description: 'Force remove the dolt directory before cloning another'
    required: false
    default: ''
outputs:
  commit:
    description: "Commit hash executed during the workflow run"
runs:
  using: 'docker'
  image: 'Dockerfile'
  post-entrypoint: './cleanup.sh'
