name: Test

on:
  push:
    #branches:
      #- main
  pull_request:
env:
  spreadsheet_id: '1ZbkUf1tAzt_Lhh1G8ezDgyU1AdUnm26xzPYLtdtWsI8'
  name: 'temp'
  range: 'A1:I99'
  branch: 'master'
  table: 'eli5'
  push: false
  remote: 'max-hoffman/dolt_action_test'
  create: 'create table if not exists eli5 (q_id text primary key, title text, selftext text, document text, subreddit text, answers json, title_urls json, selftext_urls json, answers_urls json)'
  pk: 'q_id'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull GSheet data
        id: 'sheet_to_csv'
        uses: dolthub/gsheets-to-csv@v0.1
        with:
          creds: ${{ secrets.GSHEET_CREDENTIALS }}
          tempdir: ${{ github.workspace }}
          sheets: |
            [
              { "id": "${{ env.spreadsheet_id }}" }
            ]
      - name: Dolt Import
        uses: ./ # Uses an action in the root directory
        id: 'dolt_import'
        env:
          FILES: ${{ steps.sheet_to_csv.outputs.results }}
        with:
          run: |
            dolt sql -q "${{ env.create }}"
            echo "$FILES"
            echo "$FILES" | jq -c ".[0]" | while read j; do
                eval file=$j
                dolt table import -r --pk=${{ env.pk }} --file-type csv ${{env.table}} "${file}"
            done
          remote: ${{ env.remote }}
          message: 'Dot script wrapped commit'
          push: ${{ env.push }}
          branch: ${{ env.branch }}
          commit_user_email: max@dolthub.com
          commit_author: 'Max Hoffman'
          dolthub_credential: ${{ secrets.DOLTHUB_CREDENTIAL }}
