name: Test

on:
  push:
    #branches:
      #- main
  pull_request:
env:
  spreadsheet_id: '16iUpjhWnPYDo4OUwxv1TlF9x975iPJ2WABgmpoJJdNY'
  name: 'Sheet1'
  range: 'A1:D99'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: GSheet
        id: 'update_worksheet'
        uses: jroehl/gsheet.action@v1.0.0 # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: ${{ env.spreadsheet_id }}
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getData", "args": { "range": "${{ env.name }}!${{ env.range }}" } }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Dolt Import
        uses: ./ # Uses an action in the root directory
        id: 'dolt_import'
        env:
          results: ${{ steps.update_worksheet.outputs.results }}
          tablename: 'aminals'
        with:
          run: |
            dolt sql -q "create table if not exists $tablename (id bigint primary key, name text, speed bigint)"
            echo "$results" | jq -r '.results[0].result.rawData | .[0], .[1:][] | @csv' > tmp.csv
            dolt table import -r --pk=id --file-type csv $tablename tmp.csv
          remote: 'max-hoffman/dolt_action_test'
          message: ${{ steps.date.outputs.date }}
          push: true
          branch: 'master'
          commit_user_email: max@dolthub.com
          commit_author: 'Max Hoffman'
          dolthub_credential: ${{ secrets.DOLTHUB_CREDENTIAL }}
