name: Test

on:
  push:
    branches:
      - master
  pull_request:
env:
  spreadsheet_id: '1Ihu20yDAo0Bpbc9canYgnn-XqQaRovQ6TfqKlYOxpOE'
  agent_name: 'vivant'
  branch: 'master'
  test_branch: 'test'
  new_branch: 'new'
  push: false
  dolthub_remote: 'max-hoffman/dolt_action_test'
  google_remote: 'gs://max-dolt-test-bucket'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test DoltHub remote
        uses: ./ # Uses an action in the root directory
        id: 'dolt_remote'
        with:
          run: |
            dolt sql -q "select * from aminals"
          remote: ${{ env.dolthub_remote }}
          commit_message: 'Dolt script wrapped commit'
          push: ${{ env.push }}
          branch: ${{ env.branch }}
          dolthub_credential: ${{ secrets.DOLTHUB_CREDENTIAL }}
      - name: Test Google remote
        uses: ./ # Uses an action in the root directory
        id: 'google_remote'
        with:
          run: |
            dolt sql -q "select * from aminals"
          remote: ${{ env.google_remote }}
          commit_message: 'Dolt script wrapped commit'
          push: ${{ env.push }}
          branch: ${{ env.branch }}
          google_credential: ${{ secrets.GOOGLE_CREDENTIAL }}
      - name: Test checkout branch
        uses: ./ # Uses an action in the root directory
        id: 'branch_checkout'
        with:
          run: |
            current_branch="$(dolt sql -q "select active_branch()" -r csv | head -2 | tail -1)"
            if [ "$current_branch" != ${{ env.test_branch }} ]; then
                echo "Wrong branch"
                exit 1
            fi
          remote: ${{ env.dolthub_remote }}
          commit_message: 'Dolt script wrapped commit'
          push: ${{ env.push }}
          branch: ${{ env.test_branch }}
          dolthub_credential: ${{ secrets.DOLTHUB_CREDENTIAL }}
